/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as authenticatedDashboardRouteImport } from './routes/(authenticated)/dashboard'
import { Route as publicauthSignUpIndexRouteImport } from './routes/(public)/(auth)/sign-up/index'
import { Route as publicauthSignInIndexRouteImport } from './routes/(public)/(auth)/sign-in/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatedDashboardRoute = authenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const publicauthSignUpIndexRoute = publicauthSignUpIndexRouteImport.update({
  id: '/(auth)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicauthSignInIndexRoute = publicauthSignInIndexRouteImport.update({
  id: '/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof authenticatedDashboardRoute
  '/': typeof publicIndexRoute
  '/sign-in': typeof publicauthSignInIndexRoute
  '/sign-up': typeof publicauthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof authenticatedDashboardRoute
  '/': typeof publicIndexRoute
  '/sign-in': typeof publicauthSignInIndexRoute
  '/sign-up': typeof publicauthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(authenticated)/dashboard': typeof authenticatedDashboardRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/(auth)/sign-in/': typeof publicauthSignInIndexRoute
  '/(public)/(auth)/sign-up/': typeof publicauthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dashboard' | '/' | '/sign-in' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/dashboard' | '/' | '/sign-in' | '/sign-up'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(public)'
    | '/(authenticated)/dashboard'
    | '/(public)/'
    | '/(public)/(auth)/sign-in/'
    | '/(public)/(auth)/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/(auth)/sign-up/': {
      id: '/(public)/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicauthSignUpIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/(auth)/sign-in/': {
      id: '/(public)/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicauthSignInIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRoute: typeof authenticatedDashboardRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRoute: authenticatedDashboardRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicauthSignInIndexRoute: typeof publicauthSignInIndexRoute
  publicauthSignUpIndexRoute: typeof publicauthSignUpIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicauthSignInIndexRoute: publicauthSignInIndexRoute,
  publicauthSignUpIndexRoute: publicauthSignUpIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
