/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as authenticatedSpacesIndexRouteImport } from './routes/(authenticated)/spaces/index'
import { Route as authenticatedProjectsIndexRouteImport } from './routes/(authenticated)/projects/index'
import { Route as authenticatedInboxIndexRouteImport } from './routes/(authenticated)/inbox/index'
import { Route as publicauthSignUpRouteImport } from './routes/(public)/(auth)/sign-up'
import { Route as authenticatedSpacesIdRouteImport } from './routes/(authenticated)/spaces/$id'
import { Route as publicauthSignInIndexRouteImport } from './routes/(public)/(auth)/sign-in/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatedSpacesIndexRoute =
  authenticatedSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedProjectsIndexRoute =
  authenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedInboxIndexRoute = authenticatedInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const publicauthSignUpRoute = publicauthSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatedSpacesIdRoute = authenticatedSpacesIdRouteImport.update({
  id: '/spaces/$id',
  path: '/spaces/$id',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const publicauthSignInIndexRoute = publicauthSignInIndexRouteImport.update({
  id: '/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/spaces/$id': typeof authenticatedSpacesIdRoute
  '/sign-up': typeof publicauthSignUpRoute
  '/inbox': typeof authenticatedInboxIndexRoute
  '/projects': typeof authenticatedProjectsIndexRoute
  '/spaces': typeof authenticatedSpacesIndexRoute
  '/sign-in': typeof publicauthSignInIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/spaces/$id': typeof authenticatedSpacesIdRoute
  '/sign-up': typeof publicauthSignUpRoute
  '/inbox': typeof authenticatedInboxIndexRoute
  '/projects': typeof authenticatedProjectsIndexRoute
  '/spaces': typeof authenticatedSpacesIndexRoute
  '/sign-in': typeof publicauthSignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(authenticated)/spaces/$id': typeof authenticatedSpacesIdRoute
  '/(public)/(auth)/sign-up': typeof publicauthSignUpRoute
  '/(authenticated)/inbox/': typeof authenticatedInboxIndexRoute
  '/(authenticated)/projects/': typeof authenticatedProjectsIndexRoute
  '/(authenticated)/spaces/': typeof authenticatedSpacesIndexRoute
  '/(public)/(auth)/sign-in/': typeof publicauthSignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/spaces/$id'
    | '/sign-up'
    | '/inbox'
    | '/projects'
    | '/spaces'
    | '/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/spaces/$id'
    | '/sign-up'
    | '/inbox'
    | '/projects'
    | '/spaces'
    | '/sign-in'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(public)'
    | '/(public)/'
    | '/(authenticated)/spaces/$id'
    | '/(public)/(auth)/sign-up'
    | '/(authenticated)/inbox/'
    | '/(authenticated)/projects/'
    | '/(authenticated)/spaces/'
    | '/(public)/(auth)/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/spaces/': {
      id: '/(authenticated)/spaces/'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof authenticatedSpacesIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/projects/': {
      id: '/(authenticated)/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof authenticatedProjectsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/inbox/': {
      id: '/(authenticated)/inbox/'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof authenticatedInboxIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/(auth)/sign-up': {
      id: '/(public)/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicauthSignUpRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/spaces/$id': {
      id: '/(authenticated)/spaces/$id'
      path: '/spaces/$id'
      fullPath: '/spaces/$id'
      preLoaderRoute: typeof authenticatedSpacesIdRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/(auth)/sign-in/': {
      id: '/(public)/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicauthSignInIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedSpacesIdRoute: typeof authenticatedSpacesIdRoute
  authenticatedInboxIndexRoute: typeof authenticatedInboxIndexRoute
  authenticatedProjectsIndexRoute: typeof authenticatedProjectsIndexRoute
  authenticatedSpacesIndexRoute: typeof authenticatedSpacesIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedSpacesIdRoute: authenticatedSpacesIdRoute,
  authenticatedInboxIndexRoute: authenticatedInboxIndexRoute,
  authenticatedProjectsIndexRoute: authenticatedProjectsIndexRoute,
  authenticatedSpacesIndexRoute: authenticatedSpacesIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicauthSignUpRoute: typeof publicauthSignUpRoute
  publicauthSignInIndexRoute: typeof publicauthSignInIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicauthSignUpRoute: publicauthSignUpRoute,
  publicauthSignInIndexRoute: publicauthSignInIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
